version: 2
updates:

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  labels:
  - dependencies
  - github-actions

- package-ecosystem: gradle
  directory: /
  schedule:
    interval: daily
  labels:
  - dependencies
  - gradle
